  name: actionsPractise
  on:
   workflow_dispatch: 
  env:
    FIRST_NAME: Abhinav
  jobs:
   my_first_job:
    env:
      LAST_NAME: UPADHYAY
    name: :my first job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Greetings
        run: echo "Hello World"
        

      - name: List Files
        run: ls -la
        run: echo "Abhinav ${{vars.Sirname}}
 

    
  
