  name: actionsPractise
  on:
   workflow_dispatch: 
  jobs:
   my_first_job:
    name: :my first job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Greetings
        run: echo "Hello World"

      - name: List Files
        run: ls -la
 

    
  
